name: Cargo Publish
run-name: Publish new version for commit  ${{ github.sha }} to crates.io

on:
  release: 
    types: [ published ]

jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    # Publish crate
    - uses: katyo/publish-crates@v2
      with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
